package model;

public enum StatusTela {
	
	VALORESNULOS ,INCLUIR, LISTAR, EDITAR, EXCLUIR, ENDERECOCADASTRADO, ENDERECONAOCADASTRADO, ENDERECOEDITADO, ERROEDITARENDERECO, ENDERECOERRO, FUNCIONARIEDITADO, ERROAOEDITAROFUNCIONARIO, FUNCIONARIOCADASTRADO, ERROCADASTROFUNCIONARIO, ERROAOCADASTRARENDERECO, NAOEXIBIRMENSSAGEM, FUNCIONARIOJACADASTRADO, USUARIOJAEXISTENTE;

}
