package model;

public enum StatusTela {
	
	VALORESNULOS ,INCLUIR, LISTAR, EDITAR, EXCLUIR,   FUNCIONARIEDITADO, ERROAOEDITAROFUNCIONARIO, FUNCIONARIOCADASTRADO, ERROCADASTROFUNCIONARIO, NAOEXIBIRMENSSAGEM, FUNCIONARIOJACADASTRADO, USUARIOJAEXISTENTE,

	//Endereco
	 ENDERECOCADASTRADO, ERROCADASTRARENDERECO, ENDERECOALTERADO, ERROALTERARENDERECO;
	
}
